Implementando o método que calcula a aliquota de forma dinamica
clarabcerq/calcInvestment pull request #1
Opened 2024-12-11 16:25 UTC by clarabcerq

2024-12-11 17:36 UTC, jadercerq commented on src/main/java/org/example/CalculoTaxaLiquida.java
> +    public double calculoAliquota(int periodo) {
deve ser colocando uma validação onde o valor periodo tem que ser maior que zero, por que caso o usuario coloque zero vai pegar a aliquota de 15%

2024-12-11 17:37 UTC, jadercerq commented on src/main/java/org/example/CalculoTaxaLiquida.java
>      //3- Imposto de Renda. Como o investimento é de 2 anos, a alíquota de IR será de 15%.
Remover comentário

2024-12-11 17:37 UTC, jadercerq commented on src/main/java/org/example/CalculoTaxaLiquida.java
> +    //private double aliquota;
Remover linha

2024-12-11 17:39 UTC, jadercerq requested changes
Verifique os comentários

2024-12-21 20:06 UTC, clarabcerq commented on src/main/java/org/example/CalculoTaxaLiquida.java
>      //3- Imposto de Renda. Como o investimento é de 2 anos, a alíquota de IR será de 15%.
Feito

2024-12-21 20:06 UTC, clarabcerq commented on src/main/java/org/example/CalculoTaxaLiquida.java
> +    //private double aliquota;
Feito

2024-12-21 20:07 UTC, clarabcerq commented on src/main/java/org/example/CalculoTaxaLiquida.java
> +    public double calculoAliquota(int periodo) {
Feito

2024-12-23 12:40 UTC, jadercerq approved these changes

2024-12-28 18:44 UTC, merged